### ISSUE TITLE
Cross-browser Reader testing

### ISSUE THREAD

**Issue by robwhitaker** [robwhitaker/MMPWebsiteV2#46]
- Note: currently completely untested in desktop Safari

**Comment by larouxn** [comment]
Tested in latest Chrome, Safari, Firefox, Opera, Edge, IE 11, Mobile Chrome, and Mobile Safari. Works well in all browsers I tested _except_ Edge, in which it's 95% broken.

Also, though mobile works surprisingly well, it is super annoying to use thanks to the hiding Chrome bar which triggers reflows and I find I'm constantly selecting the text since there's so much. 😑

Issues created: #93, #94, #95, #96
